add secred check
Added a step to check if the SYNC_PAT secret is empty before proceeding.

diff --git a/.github/workflows/sync.yml b/.github/workflows/sync.yml
--- a/.github/workflows/sync.yml
+++ b/.github/workflows/sync.yml
@@ -13,6 +13,15 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
+          
+      - name: Check if Secret is Empty
+        run: |
+          if [ -z "${{ secrets.SYNC_PAT }}" ]; then
+            echo "ERROR: The SYNC_PAT secret is empty or missing!"
+            exit 1
+          else
+            echo "SUCCESS: The secret is loaded and ready."
+          fi
 
       - name: Force Push to Destination
         run: |
